/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
Title: Stylized planet
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame} from '@react-three/fiber';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/public/scene.gltf');
  const { actions } = useAnimations(animations, group);

  // Use useFrame to update the rotation in each frame
  useFrame((state, delta) => {
    // Rotate the entire group around the Y-axis in each frame
    group.current.rotation.y += 0.005; // Adjust the rotation speed as needed
  });

  return (
    <group ref={group} {...props} dispose={null} scale={3}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-1.54, -0.064, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Clouds_1">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Clouds} />
              </group>
              <group name="Planet_2">
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Planet} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/public/scene.gltf')
